Iiwa_pub_sub:
  ros__parameters:
    traj_duration: 30.0
    acc_duration: 0.5
    total_time: 30.0
    trajectory_len: 300
    Kp: 5
    end_position.x: 0.7
    end_position.y: -0.5
    end_position.z: 0.8
